CREATE TABLE body_datas 
(
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    sid VARCHAR(255) NOT NULL,
    T FLOAT  NOT NULL,
    hb INTEGER NOT NULL,
    bo INTEGER NOT NULL,
    ctime TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);